---
# Docker-compose file for Kafdrop service

version: "3.8"

networks:
  internal:

volumes:
  kafdrop:
  nginx:

services:
  files-composer:
    volumes:
    - kafdrop:/app
    - nginx:/etc/nginx
    image: public.ecr.aws/compose-x/ecs-files-composer:latest
    networks:
      - internal
    deploy:
      labels:
        ecs.task.family: kafdrop
        ecs.depends.condition: SUCCESS

  nginx:
    image: ${REGISTRY_URI}kafdrop-nginx:${IMAGE_TAG:-latest}
    volumes:
    - nginx:/etc/nginx/ssl:ro
    networks:
      - internal
    build:
      context: nginx
    deploy:
      labels:
        ecs.task.family: kafdrop
      replicas: 1
      resources:
        reservations:
          cpus: 0.2
          memory: 128M
    ports:
    - 443:443
    depends_on:
      - files-composer
      - kafdrop
    x-ecr:
      InterpolateWithDigest: true

  kafdrop:
    image: public.ecr.aws/compose-x/amazoncorretto:11
    ports:
    - 9000:9000
    volumes:
    - kafdrop:/app:ro
    depends_on:
      - files-composer
    deploy:
      labels:
        ecs.task.family: kafdrop
      replicas: 1
      resources:
        reservations:
          cpus: 0.5
          memory: 1GB
    x-iam:
      PermissionsBoundary: ccoe/js-developer
    entrypoint: ["/bin/bash", "/app/start.sh"]
    networks:
      - internal
