services:
  kafka-rest-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: 0.5
          memory: 1GB
    environment:
      KAFKA_REST_CLIENT_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
      KAFKA_REST_CLIENT_ENDPOINT_IDENTIFICATION_ALGORITHM: https
      KAFKA_REST_CLIENT_SASL_MECHANISM: PLAIN
      KAFKA_REST_CLIENT_SECURITY_PROTOCOL: SASL_SSL
    image: ${REGISTRY_URI}kafka-rest-proxy:${IMAGE_TAG:-6.2}
    ports:
      - 8082:8082
    x-scaling:
      Range: 1-4
version: '3.8'
