version: '3.8'
networks:
  internal:
    x-vpc: InternalSubnets

secrets:
  azureclient:
    x-secrets:
      JsonKeys:
        - SecretKey: APP_ID
          VarName: GF_AUTH_AZUREAD_CLIENT_ID
        - SecretKey: CLIENT_SECRET
          VarName: GF_AUTH_AZUREAD_CLIENT_SECRET
        - SecretKey: AUTH_URL
          VarName: GF_AUTH_AZUREAD_AUTH_URL
        - SecretKey: TOKEN_URL
          VarName: GF_AUTH_AZUREAD_TOKEN_URL
      Name: /azuread/ddbbcdaa-a07f-4b7a-a417-97e7cd2847f3

services:
  grafana:
    environment:
      GF_AUTH_AZUREAD_ENABLED: 'true'
      GF_AUTH_AZUREAD_NAME: grafana
      GF_AUTH_AZUREAD_ROOT_URL: https://grafana.prod.compose-x.io
      GF_AUTH_AZUREAD_SCOPES: openid email profile
      GF_AUTH_AZUREAD_SCOPES_ALLOWED_DOMAINS: compose-x.io ews-network.net
      GF_DATABASE_TYPE: mysql
      GF_EXTERNAL_IMAGE_PROVIDER_STORAGE_S3_PATH: /images
      GF_EXTERNAL_IMAGE_PROVIDER_STORAGE_S3_REGION: ${AWS::Region}
      GF_SERVER_DOMAIN: grafana.prod.compose-x.io
      GF_SERVER_ROOT_URL: https://grafana.prod.compose-x.io
    networks:
      - internal
    secrets:
      - azureclient
    x-alarms:
      Predefined:
        HighRamUsageAndMaxScaledOut:
          Topics:
            - x-sns: alarms
    x-iam:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - sts:AssumeRole
                Effect: Allow
                Resource:
                  - Fn::Sub: arn:${AWS::Partition}:iam::*:role/grafana-monitoring/cw-readonly
                Sid: AccessManagementAccount
            Version: '2012-10-17'
          PolicyName: CrossAccountAccess
    x-scaling:
      Range: 1-5

volumes:
  grafana:
    x-efs:
      MacroParameters:
        EnforceIamAuth: true
      Properties:
        LifecyclePolicies: null
        TransitionToIA: AFTER_14_DAYS
x-acm:
  grafana-certs:
    MacroParameters:
      DomainNames:
        - grafana.prod.compose-x.io
        - monitoring.prod.compose-x.io
x-cluster:
  Lookup:
    ClusterName: ${ENV_NAME:-prod}
x-elbv2:
  grafanaALB:
    Listeners:
      - DefaultActions:
          - Redirect: HTTP_TO_HTTPS
        Port: 80
        Protocol: HTTP
      - Certificates:
          - x-acm: grafana-certs
        Port: 443
        Protocol: HTTPS
        Targets:
          - AuthenticateCognitoConfig:
              OnUnauthenticatedRequest: authenticate
              Scope: openid
              SessionCookieName: grafana
              SessionTimeout: 3600
              UserPoolArn: arn:aws:cognito-idp:eu-west-1:000000000000:userpool/eu-west-1_RfWYi0eAa
              UserPoolClientId: qrspbawftgzxcvjleimnuyokh
              UserPoolDomain: auth.grafana.prod.compose-x.io
            access: /
            name: grafana:grafana
    MacroParameters:
      Ingress:
        ExtSources:
          - Description: ANY
            IPv4: 0.0.0.0/0
            Name: ANY
    Properties:
      Scheme: internet-facing
      Type: application
    Services:
      - healthcheck: 3000:HTTP:7:2:15:5:/api/health
        name: grafana:grafana
        port: 3000
        protocol: HTTP
x-rds:
  grafana-db:
    Properties:
      BackupRetentionPeriod: 1
      DatabaseName: grafana
      Engine: aurora-mysql
      EngineVersion: '5.7'
      StorageEncrypted: true
    Services:
      grafana:
        Access:
          DBCluster: RO
        SecretsMappings:
          Mappings:
            host: GF_DATABASE_HOST
            password: GF_DATABASE_PASSWORD
            port: GF_DATABASE_PORT
            username: GF_DATABASE_USER
x-route53:
  PublicZone:
    Name: prod.compose-x.io
x-s3:
  data-bucket:
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    Services:
      grafana:
        Access:
          bucket: ListOnly
          objects: RW
        ReturnValues:
          BucketName: GF_EXTERNAL_IMAGE_STORAGE_S3_BUCKET
x-sns:
  alarms: {}
x-vpc:
  Lookup:
    AppSubnets:
      Tags:
        - vpc::usage: application
        - vpc::internal: 'false'
        - vpc::primary: 'true'
    InternalSubnets:
      Tags:
        - vpc::usage: application
        - vpc::internal: 'true'
        - vpc::primary: 'false'
    PublicSubnets:
      Tags:
        - vpc::usage: public
    StorageSubnets:
      Tags:
        - vpc::usage: storage
    VpcId:
      Tags:
        - Name: vpc--prod
