AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Template to create an AzureAD Client Application secret

Parameters:
  TenantId:
    Type: String
  AppId:
    Type: String
  ClientId:
    Type: String
  ClientSecret:
    Type: String
    NoEcho: True
  TokenUrl:
    Type: String
  AuthUrl:
    Type: String

Resources:
  AzureAppIdSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '/azuread/${AppId}'
      Description: !Sub "AzureAD ${AppId} Application secrets"
      SecretString: !Sub |
        {
          "TENANT_ID": "${TenantId}",
          "APP_ID": "${AppId}",
          "CLIENT_ID": "${ClientId}",
          "CLIENT_SECRET": "${ClientSecret}",
          "AUTH_URL": "${AuthUrl}",
          "TOKEN_URL": "${TokenUrl}"
        }
      Tags:
        - Key: AzureAppId
          Value: !Ref AppId
        - Key: costcentre
          Value: PD7564
        - Key: live
          Value: "no"

  AzureAppIdSecretPolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      ResourcePolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Deny
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/ccoe/developer"
            Action: "secretsmanager:GetSecretValue"
            Resource: "*"
      SecretId: !Ref AzureAppIdSecret
