---
# Docker-compose file for grafana dashboard

version: "3.8"
services:
  grafana:
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
    user: "472:0"
    build:
      context: .
      dockerfile: Dockerfile

    image: ${REGISTRY_URI}grafana:${IMAGE_TAG:-latest}
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: 0.5
          memory: 1GB
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/api/health -sq || exit 1"]

      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 1m
    volumes:
    - grafana:/var/lib/grafana

volumes:
  grafana:
