AWSTemplateFormatVersion: "2010-09-09"
Description:
  Template for JKS files stored in AWS S3 that client apps need

Parameters:
  SecretName:
    Type: String

  TruststorePassword:
    Type: String
    NoEcho: True

  KeystorePassword:
    Type: String
    NoEcho: True

Resources:
  JKSSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Ref SecretName
      Description: "JKS Passwords"
      SecretString: !Sub |
        {
          "TRUSTSTORE_PASSWORD": "${TruststorePassword}",
          "KEYSTORE_PASSWORD": "${KeystorePassword}"
        }
