AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Template to create a new AWS Secret storing credentials for Kafka Connect (Confluent)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Cluster Settings
        Parameters:
          - ClusterId
          - BootstrapEndpoint
          - BootstrapPort
          - SchemaRegistryUrl
          - ClusterName
          - ClusterConnectUsername
          - ClusterConnectPassword
      - Label:
          default: Connect consumer settings
        Parameters:
          - ClusterConsumerUsername
          - ClusterConsumerPassword
      - Label:
          default: Connect producer settings
        Parameters:
          - ClusterProducerUsername
          - ClusterProducerPassword
      - Label:
          default: Schema Registry credentials
        Parameters:
          - SchemaRegistryUsername
          - SchemaRegistryPassword

Parameters:
  ClusterId:
    Type: String
  BootstrapEndpoint:
    Type: String
  BootstrapPort:
    Type: Number
    MinValue: 1024
    MaxValue: 65535

  ClusterName:
    Type: String

  ClusterConnectUsername:
    Type: String
    NoEcho: True
  ClusterConnectPassword:
    Type: String
    NoEcho: True

  ClusterProducerUsername:
    Type: String
    NoEcho: True
  ClusterProducerPassword:
    Type: String
    NoEcho: True

  ClusterConsumerUsername:
    Type: String
    NoEcho: True
  ClusterConsumerPassword:
    Type: String
    NoEcho: True

  SchemaRegistryUrl:
    Type: String
  SchemaRegistryUsername:
    Type: String
    NoEcho: True
  SchemaRegistryPassword:
    Type: String
    NoEcho: True

Resources:
  KafkaSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '/kafka/${AWS::Region}/${ClusterId}/${ClusterName}'
      Description: "Secret for Confluent Connect Cluster credentials"
      SecretString: !Sub |
        {
        	"CONNECT_BOOTSTRAP_SERVERS": "${BootstrapEndpoint}:${BootstrapPort}",
            "CONNECT_SASL_JAAS_CONFIG": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${ClusterConnectUsername}\" password=\"${ClusterConnectPassword}\";",
        	"CONNECT_SCHEMA_REGISTRY_URL": "${SchemaRegistryUrl}",
        	"CONNECT_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO": "${SchemaRegistryUsername}:${SchemaRegistryPassword}",

        	"CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL": "${SchemaRegistryUrl}",
        	"CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO": "${SchemaRegistryUsername}:${SchemaRegistryPassword}",

        	"CONNECT_PRODUCER_SASL_JAAS_CONFIG": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${ClusterProducerUsername}\" password=\"${ClusterProducerPassword}\";",

        	"CONNECT_CONSUMER_SASL_JAAS_CONFIG": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${ClusterConsumerUsername}\" password=\"${ClusterConsumerPassword}\";",
            "CONNECT_CONSUMER_VALUE_CONVERTER_SCHEMA_REGISTRY_URL": "${SchemaRegistryUrl}",
        	"CONNECT_CONSUMER_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO": "${SchemaRegistryUsername}:${SchemaRegistryPassword}"
        }
