---
# Configuration to export the prometheus config from traefik to AWS CW

version: "3.8"
services:
  traefik:
    labels:
      container_name: traefik
    x-prometheus:
      ContainersInsights:
        EnableCWAgentDebug: true
        CustomRules:
          - ExporterPort: 8080
            ExporterPath: /metrics
            EmfProcessors:
              - source_labels:
                  - container_name
                label_matcher: "^traefik.*$"
                metric_selectors:
                  - "^traefik_entrypoint_requests_total$"
                dimensions:
                  - - ClusterName
                    - TaskDefinitionFamily
                    - code
                    - entrypoint
                    - method
                    - protocol
